### ISSUE TITLE
切换成camera2就不行了吗

### ISSUE THREAD

**Issue by ZhongJianHui** [rome753/webrtc-android-tutorial#4]
切换成Camera2Enumerator运行就直接报错了
java.lang.IllegalArgumentException: Buffer must be at least 1035840 bytes, but was 518400
                                                                                  	at org.webrtc.JavaI420Buffer.checkCapacity(JavaI420Buffer.java:47)
                                                                                  	at org.webrtc.JavaI420Buffer.wrap(JavaI420Buffer.java:71)

**Comment by ZhongJianHui** [comment]
EglProcessor滤镜处理的
